"""
fig_ranking_recovery.py
Generates fig_ranking_recovery.pdf — Spearman ρ and Kendall τ between
the noisy-data ranking and the oracle ranking, comparing LPI-B² against
classical accuracy.

Paper: Figure 11 / Section "Ranking recovery under label noise".
Inputs (quick mode):
    data/postproc_02_classical_vs_lbi.csv  (intermediate, generated by
    fig_estimator_correlations.py if not present)
    data/table_multiarch_def_yc.csv
    data/table_multiarch_def_sep05.csv
    data/table_multiarch_def_sep1_W.csv
    data/table_multiarch_def_sep2.csv
    data/table_multiarch_def_sep2_W.csv
Output: outputs/fig_ranking_recovery.pdf

Run:
    python figures/fig_ranking_recovery.py
"""
import sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path
from scipy.stats import spearmanr, kendalltau

ROOT    = Path(__file__).resolve().parent.parent
DATA    = ROOT / "data"
OUT     = ROOT / "outputs"
OUT.mkdir(exist_ok=True)

plt.rcParams.update({"font.size": 11, "axes.labelsize": 12, "axes.titlesize": 12,
                     "legend.fontsize": 10, "figure.dpi": 110})
TAG = "[fig_ranking_recovery]"

df02 = pd.read_csv(DATA / "postproc_02_classical_vs_lbi.csv")
df02["absorbs"] = df02["frac_A_proxy"] < 0.05
df02["mu_composite"] = df02.apply(
    lambda r: r["mu_avg"] if not r["absorbs"] else 0.0, axis=1
)

SEP_FILES = {
    "1.0":  DATA / "table_multiarch_def_yc.csv",
    "0.5":  DATA / "table_multiarch_def_sep05.csv",
    "1.0W": DATA / "table_multiarch_def_sep1_W.csv",
    "2.0":  DATA / "table_multiarch_def_sep2.csv",
    "2.0W": DATA / "table_multiarch_def_sep2_W.csv",
}

for label, path in SEP_FILES.items():
    if not path.exists():
        print(f"{TAG} ERROR: missing {path}"); sys.exit(1)

frames = []
for sep_label, path in SEP_FILES.items():
    df = pd.read_csv(path)
    df["class_sep"] = sep_label
    frames.append(df)
data = pd.concat(frames, ignore_index=True)

proxy_cols = df02[["arch", "seed", "flip_y", "frac_A_proxy", "absorbs", "mu_composite"]].copy()
data = data.merge(proxy_cols, on=["arch", "seed", "flip_y"], how="left")
data["absorbs"] = data["absorbs"].fillna(False)
data["mu_composite"] = data.apply(
    lambda r: r["mu_composite"] if pd.notna(r["mu_composite"]) else r["mu_avg"], axis=1
)

ARCHS = ["LR", "RF", "SVM", "GB", "MLP"]

def rank_series(series):
    return series.rank(ascending=False).astype(int)

records = []
for (sep, seed), grp in data.groupby(["class_sep", "seed"]):
    oracle_phi = grp["flip_y"].min()
    oracle_row = grp[grp["flip_y"] == oracle_phi].set_index("arch")
    if oracle_row.empty:
        continue
    oracle_rank = rank_series(oracle_row["mu_avg"])

    for phi, phi_grp in grp[grp["flip_y"] != oracle_phi].groupby("flip_y"):
        phi_row = phi_grp.set_index("arch")
        if set(ARCHS) - set(phi_row.index):
            continue
        phi_row = phi_row.reindex(ARCHS)
        o_rank  = oracle_rank.reindex(ARCHS)

        rank_acc  = rank_series(phi_row["cv_acc"])
        rank_mu   = rank_series(phi_row["mu_avg"])
        rank_comp = rank_series(phi_row["mu_composite"])

        def corr_pair(r_noisy, r_oracle):
            rho, _ = spearmanr(r_oracle.values, r_noisy.values)
            tau, _ = kendalltau(r_oracle.values, r_noisy.values)
            return rho, tau

        rho_acc,  tau_acc  = corr_pair(rank_acc,  o_rank)
        rho_mu,   tau_mu   = corr_pair(rank_mu,   o_rank)
        rho_comp, tau_comp = corr_pair(rank_comp, o_rank)

        records.append({"class_sep": sep, "flip_y": phi, "seed": seed,
                        "rho_accuracy": rho_acc,       "tau_accuracy": tau_acc,
                        "rho_mu_avg":   rho_mu,        "tau_mu_avg":   tau_mu,
                        "rho_lpi_composite": rho_comp, "tau_lpi_composite": tau_comp})

per_seed = pd.DataFrame(records)

agg_global = per_seed.groupby("flip_y").agg(
    rho_acc_mean=("rho_accuracy", "mean"),        rho_acc_std=("rho_accuracy", "std"),
    rho_mu_mean=("rho_mu_avg", "mean"),           rho_mu_std=("rho_mu_avg", "std"),
    rho_comp_mean=("rho_lpi_composite", "mean"),  rho_comp_std=("rho_lpi_composite", "std"),
    tau_acc_mean=("tau_accuracy", "mean"),        tau_acc_std=("tau_accuracy", "std"),
    tau_mu_mean=("tau_mu_avg", "mean"),           tau_mu_std=("tau_mu_avg", "std"),
    tau_comp_mean=("tau_lpi_composite", "mean"),  tau_comp_std=("tau_lpi_composite", "std"),
).reset_index()

STYLES = {
    "accuracy":       dict(color="#888888", linestyle="--",
                           marker="o", linewidth=1.8, markersize=7,
                           label="Accuracy (classical)"),
    "mu_avg":         dict(color="#1f77b4", linestyle="-",
                           marker="s", linewidth=2.0, markersize=8,
                           label=r"$\hat{\mu}_{avg}$ (LPI-B$^2$)"),
    "lpi_composite":  dict(color="#2ca02c", linestyle="-",
                           marker="^", linewidth=2.0, markersize=8,
                           label="LPI-B² composite"),
}

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
phis = agg_global["flip_y"].values

for ax, stat in zip(axes, ["rho", "tau"]):
    for key, (mean_col, std_col) in [
        ("accuracy",      (f"{stat}_acc_mean",  f"{stat}_acc_std")),
        ("mu_avg",        (f"{stat}_mu_mean",   f"{stat}_mu_std")),
        ("lpi_composite", (f"{stat}_comp_mean", f"{stat}_comp_std")),
    ]:
        s = STYLES[key]
        means = agg_global[mean_col].values
        stds  = agg_global[std_col].values
        ax.plot(phis, means, color=s["color"], linestyle=s["linestyle"],
                marker=s["marker"], linewidth=s["linewidth"], markersize=s["markersize"],
                label=s["label"])
        ax.fill_between(phis, means - stds, means + stds, color=s["color"], alpha=0.15)

    ylabel = "Spearman ρ" if stat == "rho" else "Kendall τ"
    ax.set_xlabel("Label noise φ")
    ax.set_ylabel(ylabel)
    ax.set_title(f"{ylabel} vs oracle ranking")
    ax.legend()
    ax.set_ylim(-0.1, 1.05)
    ax.axhline(1.0, color="k", ls=":", lw=0.8, alpha=0.4)
    ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.4)

fig.suptitle("Ranking recovery: LPI-B² vs classical accuracy\n"
             "(oracle = µ̂_avg at φ=0 for sep=1.0)",
             fontsize=11)
plt.tight_layout()

out_fig = OUT / "fig_ranking_recovery.pdf"
fig.savefig(out_fig, bbox_inches="tight")
fig.savefig(str(out_fig).replace(".pdf", ".png"), bbox_inches="tight", dpi=150)
plt.close()
print(f"{TAG} Saved: {out_fig}")
